#!/bin/bash


read_dir(){
    for file in `ls -a $1`
    do
        if [ -d $1"/"$file  ]
        then
            if [[ $file != '.' && $file != '..'  ]]
            then
                read_dir $1"/"$file $2
            fi
        else
			sed -i "s/quick_gin/$2/" $1"/"$file
        fi
    done

}

which "git" > /dev/null
if [ $? -eq 0  ]
then
	git clone https://github.com/codeAB/quick_gin.git $1
	cd $1
	rm -rf $1/.git $1/.idea
	read_dir `pwd` $1
	echo "success"
	exit 0
else
	echo "git not exists"
	exit -1
fi

