#!/bin/bash


read_dir(){
    for file in `ls -a $1`
    do
        if [ -d $1"/"$file  ]
        then
            if [[ $file != '.' && $file != '..'  ]]
            then
                read_dir $1"/"$file $2
            fi
        else
			sed -i "s/quick_gin/$2/" $1"/"$file
        fi
    done

}

which "git" > /dev/null
if [ $? -eq 0  ]
then
	git clone https://github.com/codeAB/quick_gin.git $1 > /dev/null
	cd $1
	rm -rf .git .idea
	read_dir `pwd` $1
	g=`go version`
	version=${g:13:4}
	sed -i "s/1.13/$version/" go.mod
	exit 0
else
	echo "git not installed"
	exit -1
fi

